spring:
  profiles:
    active: dev
  application:
    name: library-api
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
#server:
#  error:
#    include-stacktrace: always
#    include-exception: true
#    include-message: ALWAYS
#    include-binding-errors: NEVER