spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/library_api}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:858733}
    driver-class-name: org.postgresql.Driver

# Logging
logging:
  level:
    root: INFO
    com.unichristus: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} %X{traceId} - %msg%n"

# JWT Config
jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION_MILIS:86400000}

# Minio
minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: password123
  bucket:
    files: book-files
    max-size-mb: 10